[KYUUBI #7289] Release requires Java 17 or 21
### Why are the changes needed?

I hit an issue while preparing 1.11.0 RC0, which indicates I need to use a higher version of JDK for releasing.

```
[INFO] --- antlr4:4.13.1:antlr4 (default)  kyuubi-extension-spark-4-0_2.13 ---
[WARNING] Error injecting: org.antlr.mojo.antlr4.Antlr4Mojo
java.lang.UnsupportedClassVersionError: org/antlr/v4/Tool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1 (Native Method)
    at java.lang.ClassLoader.defineClass (ClassLoader.java:756)
    at java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142)
```

In https://github.com/apache/kyuubi/pull/7144, we made it always use `-release:8` for `jdk9+`, so we still produce Java 8 compatible bytecode even using JDK 17, for all modules except Spark 4.0/4.1 extension modules.

### How was this patch tested?

Will verify this in the next RC of 1.11.0

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #7289 from pan3793/release-java17.

Closes #7289

17e29bea0 [Cheng Pan] Release requires Java 17 or 21

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: Cheng Pan <chengpan@apache.org>
(cherry picked from commit eecdaaa4d78fef90d6acac9ab36cc1b9d3babe1c)
Signed-off-by: Cheng Pan <chengpan@apache.org>