org.apache.thrift.protocol.TProtocolException: Required field 'columns' is unset! Struct:TTableSchema(columns:null) 	at org.apache.hive.service.cli.thrift.TTableSchema.validate(TTableSchema.java:310) 	at org.apache.hive.service.cli.thrift.TGetResultSetMetadataResp.validate(TGetResultSetMetadataResp.java:380) 	at org.apache.hive.service.cli.thrift.TCLIService.validate(TCLIService.java:12404) 	at org.apache.hive.service.cli.thrift.TCLIService.write(TCLIService.java:12461) 	at org.apache.hive.service.cli.thrift.TCLIService.write(TCLIService.java:12430) 	at org.apache.hive.service.cli.thrift.TCLIService.write(TCLIService.java:12381) 	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:53) 	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) 	at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge.process(HadoopThriftAuthBridge.java:692) 	at org.apache.thrift.server.TThreadPoolServer.run(TThreadPoolServer.java:286) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 	at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:617) 	at java.lang.Thread.run(Thread.java:745)