[KYUUBI #5617][TEST] Make flaky test `spnego batch rest client` reliable
# :mag: Description
## Issue References 🔗

This pull request fixes #5617

## Describe Your Solution 🔧

`batch_long_time` job sleep is changed from 10 seconds to 120 seconds to avoid spark executing and exiting when deleting the batch.
When pulling the spark running log, make sure the spark driver is already running.

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

#### Behavior Without This Pull Request :coffin:
```
- basic batch rest client *** FAILED ***
  "{"success":false,"msg":"APPLICATION_NOT_FOUND"}
  Warning: Batch 1f3af615-721b-45dd-9f0f-cb976bfef988 is already in terminal state ERROR." did not contain ""success":true" (TestPrematureExit.scala:72)
- spnego batch rest client *** FAILED ***
  "{"success":false,"msg":"APPLICATION_NOT_FOUND"}
  Warning: Batch 30b1e3d6-9996-4409-8b28-eead5258fc3b is already in terminal state ERROR." did not contain ""success":true" (TestPrematureExit.scala:72)
```

```
- spnego batch rest client *** FAILED ***
  "{"success":false,"msg":"APPLICATION_NOT_FOUND"}
  Error: Failed to delete batch f20c041c-3246-4fca-9814-c4892cd83220, its current state is RUNNING" did not contain ""success":true" (TestPrematureExit.scala:72)
```

#### Behavior With This Pull Request :tada:
GA pass

#### Related Unit Tests
BatchCliSuite.scala  "basic batch rest client" "spnego batch rest client"

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [x] Pull request title is okay.
- [x] No license issues.
- [x] Milestone correctly set?
- [x] Test coverage is ok
- [x] Assignees are selected.
- [x] Minimum number of approvals
- [x] No changes are requested

**Be nice. Be informative.**

Closes #5722 from cxzl25/KYUUBI-5617.

Closes #5617

ba2ca7b38 [sychen] invalidCount
fb0586cb9 [sychen] retry
2d074572c [sychen] sleep 1 min

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Shaoyun Chen <csy@apache.org>