[KYUUBI #6067] Bump org.postgresql:postgresql from 42.6.0 to 42.7.2
Bumps [org.postgresql:postgresql](https://github.com/pgjdbc/pgjdbc) from 42.6.0 to 42.7.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/pgjdbc/pgjdbc/releases">org.postgresql:postgresql's releases</a>.</em></p>
<blockquote>
<h2>v42.7.1</h2>
<h2>Fixed regressions since 42.7.0</h2>
<ul>
<li>Revert &quot;Use canonical DateStyle name (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2925">#2925</a>)&quot; <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3035">#3035</a>)</li>
<li>Revert &quot;feat: support SET statements combining with other queries with semicolon in PreparedStatement&quot; <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3010">#3010</a>)</li>
<li>chore: use java.release=8 when building pgjdbc from the generated source distribution <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3038">#3038</a>), the driver uses Java 8 methods only</li>
</ul>
<h2>Changes</h2>
<ul>
<li>Apply connectTimeout before SSLSocket.startHandshake to avoid infinite wait in case the connection is broken <a href="https://github.com/davecramer"><code>​davecramer</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3040">#3040</a>)</li>
<li>perf: improve performance of PreparedStatement.setBlob, BlobInputStream, and BlobOutputStream with dynamic buffer sizing <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3044">#3044</a>)</li>
<li>fix: avoid timezone conversions when sending LocalDateTime to the database <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2852">#2852</a>)</li>
<li>fix: support waffle-jna 2.x and 3.x by using reflective approach for ManagedSecBufferDesc <a href="https://github.com/chrullrich"><code>​chrullrich</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2720">#2720</a>)</li>
</ul>
<h2>🧰 Maintenance</h2>
<ul>
<li>chore: bump Gradle to 8.5 <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3045">#3045</a>)</li>
<li>chore: use Java 17 for building pgjdbc, and use --release 8 to target Java 8, add tests with Java 21 and 22 <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3026">#3026</a>)</li>
<li>fedora/rpm: move source build to java-17-openjdk-devel <a href="https://github.com/praiskup"><code>​praiskup</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3036">#3036</a>)</li>
<li>Update site 42 7 0 <a href="https://github.com/davecramer"><code>​davecramer</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3004">#3004</a>)</li>
<li>prepared for release 42.7.1 update changelogs <a href="https://github.com/davecramer"><code>​davecramer</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3037">#3037</a>)</li>
</ul>
<h2>⬆️ Dependencies</h2>
<ul>
<li>fix(deps): update dependency org.checkerframework:org.checkerframework.gradle.plugin to v0.6.36 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3060">#3060</a>)</li>
<li>chore(deps): update plugin biz.aqute.bnd.builder to v7 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3034">#3034</a>)</li>
<li>fix(deps): update dependency com.github.spotbugs:com.github.spotbugs.gradle.plugin to v6 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3056">#3056</a>)</li>
<li>fix(deps): update dependency com.github.spotbugs:com.github.spotbugs.gradle.plugin to v5.2.5 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3032">#3032</a>)</li>
<li>chore(deps): update codecov/codecov-action digest to b0466b4 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3059">#3059</a>)</li>
<li>fix(deps): update checkerframework to v3.41.0 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3058">#3058</a>)</li>
<li>fix(deps): update logback to v1.2.13 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3053">#3053</a>)</li>
<li>chore(deps): update codecov/codecov-action digest to 438fa9e <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3051">#3051</a>)</li>
<li>fix(deps): update dependency spotbugs to v4.8.2 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3052">#3052</a>)</li>
<li>chore: bump Gradle to 8.5 <a href="https://github.com/vlsi"><code>​vlsi</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3045">#3045</a>)</li>
<li>fix(deps): update dependency org.ops4j.pax.url:pax-url-aether to v2.6.14 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3030">#3030</a>)</li>
<li>chore(deps): update plugin org.nosphere.gradle.github.actions to v1.4.0 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3031">#3031</a>)</li>
<li>chore(deps): update dependency ubuntu to v22 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3033">#3033</a>)</li>
<li>fix(deps): update checkerframework <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3027">#3027</a>)</li>
<li>fix(deps): update dependency spotbugs to v4.8.1 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3023">#3023</a>)</li>
<li>fix(deps): update dependency uk.org.webcompere:system-stubs-jupiter to v2.1.5 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3024">#3024</a>)</li>
<li>fix(deps): update jmh to v1.37 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3025">#3025</a>)</li>
<li>fix(deps): update dependency com.google.errorprone:error_prone_core to v2.23.0 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3022">#3022</a>)</li>
<li>fix(deps): update junit5 monorepo to v5.10.1 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3015">#3015</a>)</li>
<li>chore(deps): update plugin com.github.burrunan.s3-build-cache to v1.7 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3016">#3016</a>)</li>
<li>chore(deps): update dependency com.typesafe.play:sbt-plugin to v2.9.0 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3021">#3021</a>)</li>
<li>fix(deps): update dependency checkstyle to v10.12.5 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3020">#3020</a>)</li>
<li>chore(deps): update codecov/codecov-action digest to 920a494 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3019">#3019</a>)</li>
<li>chore(deps): update actions/github-script action to v7 <a href="https://github.com/renovate-bot"><code>​renovate-bot</code></a> (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3018">#3018</a>)</li>
</ul>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md">org.postgresql:postgresql's changelog</a>.</em></p>
<blockquote>
<h1>Changelog</h1>
<p>Notable changes since version 42.0.0, read the complete <a href="https://jdbc.postgresql.org/documentation/changelog.html">History of Changes</a>.</p>
<p>The format is based on <a href="http://keepachangelog.com/en/1.0.0/">Keep a Changelog</a>.</p>
<h2>[Unreleased]</h2>
<h3>Changed</h3>
<h3>Added</h3>
<ul>
<li>feat: Add PasswordUtil for encrypting passwords client side [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3082">#3082</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3082">pgjdbc/pgjdbc#3082</a>)</li>
</ul>
<h3>Fixed</h3>
<h2>[42.7.1] (2023-12-06 08:34:00 -0500)</h2>
<h3>Changed</h3>
<ul>
<li>perf: improve performance of PreparedStatement.setBlob, BlobInputStream, and BlobOutputStream with dynamic buffer sizing [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3044">#3044</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3044">pgjdbc/pgjdbc#3044</a>)</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>fix: Apply connectTimeout before SSLSocket.startHandshake to avoid infinite wait in case the connection is broken [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3040">#3040</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3040">pgjdbc/pgjdbc#3040</a>)</li>
<li>fix: support waffle-jna 2.x and 3.x by using reflective approach for ManagedSecBufferDesc [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2720">#2720</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2720">pgjdbc/pgjdbc#2720</a>) Fixes [Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2690">#2690</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2720">pgjdbc/pgjdbc#2720</a>).</li>
<li>fix: NoSuchMethodError on ByteBuffer#position When Running on Java 8  when accessing arrays, fixes [Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3014">#3014</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3014">pgjdbc/pgjdbc#3014</a>)</li>
<li>Revert &quot;[PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2925">#2925</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2925">pgjdbc/pgjdbc#2925</a>) Use canonical DateStyle name&quot; [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3035">#3035</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3035">pgjdbc/pgjdbc#3035</a>)
Fixes  [Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3008">#3008</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3008">pgjdbc/pgjdbc#3008</a>)</li>
<li>Revert &quot;[PR #<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2973">#2973</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2973">pgjdbc/pgjdbc#2973</a>) feat: support SET statements combining with other queries with semicolon in PreparedStatement&quot; [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3010">#3010</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3010">pgjdbc/pgjdbc#3010</a>)
Fixes [Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3007">#3007</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3007">pgjdbc/pgjdbc#3007</a>)</li>
<li>fix: avoid timezone conversions when sending LocalDateTime to the database <a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3010">#2852</a>  Fixes [Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/1390">#1390</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/1390">pgjdbc/pgjdbc#1390</a>)
,[Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2850">#2850</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2850">pgjdbc/pgjdbc#2850</a>)
Closes [Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/1391">#1391</a>(https://redirect.github.com/pgjdbc/pgjdbc/issues/1391)</li>
</ul>
<h2>[42.7.0] (2023-11-20 09:33:00 -0500)</h2>
<h3>Changed</h3>
<ul>
<li>fix: Deprecate for removal PGPoint.setLocation(java.awt.Point) to cut dependency to <code>java.desktop</code> module. [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2967">#2967</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2967">pgjdbc/pgjdbc#2967</a>)</li>
<li>feat: return all catalogs for getCatalogs metadata query closes [ISSUE <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2949">#2949</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2949">pgjdbc/pgjdbc#2949</a>) [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2953">#2953</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2953">pgjdbc/pgjdbc#2953</a>)</li>
<li>feat: support SET statements combining with other queries with semicolon in PreparedStatement [PR #<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2973">#2973</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2973">pgjdbc/pgjdbc#2973</a>)</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>chore: add styleCheck Gradle task to report style violations [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2980">#2980</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2980">pgjdbc/pgjdbc#2980</a>)</li>
<li>fix: Include currentXid in &quot;Error rolling back prepared transaction&quot; exception message [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2978">#2978</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2978">pgjdbc/pgjdbc#2978</a>)</li>
<li>fix: add varbit as a basic type inside the TypeInfoCache [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2960">#2960</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2960">pgjdbc/pgjdbc#2960</a>)</li>
<li>fix: Fix failing tests for version 16.  [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2962">#2962</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2962">pgjdbc/pgjdbc#2962</a>)</li>
<li>fix: allow setting arrays with ANSI type name [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2952">#2952</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2952">pgjdbc/pgjdbc#2952</a>)</li>
<li>feat: Use KeepAlive to confirm LSNs [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2941">#2941</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2941">pgjdbc/pgjdbc#2941</a>)</li>
<li>fix: put double ' around log parameter [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2936">#2936</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2936">pgjdbc/pgjdbc#2936</a>) fixes [ISSUE <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2935">#2935</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2935">pgjdbc/pgjdbc#2935</a>)</li>
<li>fix: Fix Issue <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2928">#2928</a> number of ports not equal to number of servers in datasource [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2929">#2929</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2929">pgjdbc/pgjdbc#2929</a>)</li>
<li>fix: Use canonical DateStyle name (<a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2925">#2925</a>) fixes <a href="https://redirect.github.com/pgbouncer/pgbouncer/issues/776">pgbouncer issue</a></li>
<li>fix: Method getFastLong should be able to parse all longs [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2881">#2881</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2881">pgjdbc/pgjdbc#2881</a>)</li>
<li>docs: Fix typos in info.html [PR <a href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2860">#2860</a>](<a href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2860">pgjdbc/pgjdbc#2860</a>)</li>
</ul>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a href="https://github.com/pgjdbc/pgjdbc/commits">compare view</a></li>
</ul>
</details>
<br />

[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.postgresql:postgresql&package-manager=maven&previous-version=42.6.0&new-version=42.7.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `dependabot rebase` will rebase this PR
- `dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `dependabot merge` will merge this PR after your CI passes on it
- `dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `dependabot cancel merge` will cancel a previously requested merge and block automerging
- `dependabot reopen` will reopen this PR if it is closed
- `dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/apache/kyuubi/network/alerts).

</details>

Closes #6067 from dependabot[bot]/dependabot/maven/org.postgresql-postgresql-42.7.2.

Closes #6067

55ea68732 [dependabot[bot]] :arrow_up: Bump org.postgresql:postgresql from 42.6.0 to 42.7.2

Authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Signed-off-by: Cheng Pan <chengpan@apache.org>