[KYUUBI #5317] [Bug][1.7] Hive Connector throws NotSerializableException on reading Hive Avro partitioned table
# :mag: Description
## Issue References 🔗

This pull request fixes #5317

## Describe Your Solution 🔧

cherry-pick

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

#### Behavior Without This Pull Request :coffin:
```
Error: ] /home/runner/work/kyuubi/kyuubi/extensions/spark/kyuubi-spark-connector-hive/src/test/scala/org/apache/kyuubi/spark/connector/hive/HiveQuerySuite.scala:169: too many arguments (4) for method withTempPartitionedTable: (spark: org.apache.spark.sql.SparkSession, table: String)(f: => Unit)Unit
Note that 'hiveTable' is not a parameter name of the invoked method.
```

https://github.com/apache/kyuubi/actions/runs/6903431853/job/18782106774

#### Behavior With This Pull Request :tada:

#### Related Unit Tests
org.apache.kyuubi.spark.connector.hive.HiveQuerySuite

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [ ] Pull request title is okay.
- [ ] No license issues.
- [ ] Milestone correctly set?
- [ ] Test coverage is ok
- [ ] Assignees are selected.
- [ ] Minimum number of approvals
- [ ] No changes are requested

**Be nice. Be informative.**

Closes #5741 from cxzl25/KYUUBI-5317-1.7.

Closes #5317

482b829b6 [zhaomin] [KYUUBI #5317] [Bug] Hive Connector throws NotSerializableException on reading Hive Avro partitioned table

Authored-by: zhaomin <zhaomin1423@163.com>
Signed-off-by: Shaoyun Chen <csy@apache.org>