1. set operation log to rootlogdir/operation_logs/username/sessionid
2. fix delete log dir bug:

java.io.FileNotFoundException: File does not exist: /home/hadoop/data/apache-spark/spark-2.1.2-bin-2.1.2/operation_logs/hzyaoqin/7c8789b1-5dfc-4eb2-bc9e-243e1ad6446e/f8ef9615-5a13-471d-a091-8ea83f32cd30
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2275)
	at org.apache.hadoop.hive.ql.session.OperationLog$LogFile.remove(OperationLog.java:163)
	at org.apache.hadoop.hive.ql.session.OperationLog.close(OperationLog.java:121)
	at yaooqinn.kyuubi.operation.KyuubiOperation.cleanupOperationLog(KyuubiOperation.scala:190)
	at yaooqinn.kyuubi.operation.KyuubiOperation.close(KyuubiOperation.scala:199)
	at yaooqinn.kyuubi.operation.OperationManager.closeOperation(OperationManager.scala:131)
	at yaooqinn.kyuubi.session.KyuubiSession$$anonfun$close$1.apply(KyuubiSession.scala:319)
	at yaooqinn.kyuubi.session.KyuubiSession$$anonfun$close$1.apply(KyuubiSession.scala:318)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at yaooqinn.kyuubi.session.KyuubiSession.close(KyuubiSession.scala:318)
	at yaooqinn.kyuubi.session.SessionManager.closeSession(SessionManager.scala:264)
	at yaooqinn.kyuubi.server.BackendService.closeSession(BackendService.scala:78)
	at yaooqinn.kyuubi.server.FrontendService$FeTServerEventHandler$$anonfun$deleteContext$1$$anonfun$1.apply$mcV$sp(FrontendService.scala:96)
	at yaooqinn.kyuubi.server.FrontendService$FeTServerEventHandler$$anonfun$deleteContext$1$$anonfun$1.apply(FrontendService.scala:96)
	at yaooqinn.kyuubi.server.FrontendService$FeTServerEventHandler$$anonfun$deleteContext$1$$anonfun$1.apply(FrontendService.scala:96)
	at scala.util.Try$.apply(Try.scala:192)
	at yaooqinn.kyuubi.server.FrontendService$FeTServerEventHandler$$anonfun$deleteContext$1.apply(FrontendService.scala:96)
	at yaooqinn.kyuubi.server.FrontendService$FeTServerEventHandler$$anonfun$deleteContext$1.apply(FrontendService.scala:93)
	at scala.Option.foreach(Option.scala:257)
	at yaooqinn.kyuubi.server.FrontendService$FeTServerEventHandler.deleteContext(FrontendService.scala:93)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:300)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)