[KYUUBI #1804][FOLLOWUP][GA] Avoid push docker image for forked repos
<!--
Thanks for sending a pull request!

Here are some tips for you:
  1. If this is your first time, please read our contributor guidelines: https://kyuubi.readthedocs.io/en/latest/community/contributions.html
  2. If the PR is related to an issue in https://github.com/apache/incubator-kyuubi/issues, add '[KYUUBI #XXXX]' in your PR title, e.g., '[KYUUBI #XXXX] Your PR title ...'.
  3. If the PR is unfinished, add '[WIP]' in your PR title, e.g., '[WIP][KYUUBI #XXXX] Your PR title ...'.
-->

### _Why are the changes needed?_
<!--
Please clarify why the changes are needed. For instance,
  1. If you add a feature, you can talk about the use case of it.
  2. If you fix a bug, you can clarify why it is a bug.
-->

```
Run docker/login-actionv[1](https://github.com/cfmcgrady/incubator-kyuubi/runs/5088959102?check_suite_focus=true#step:3:1)
  with:
    ecr: auto
    logout: true
Error: Username and password required
```

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

Closes #1863 from cfmcgrady/avoid-publish-image.

Closes #1804

5d7711bc [Fu Chen] [GA] avoid push docker image for forked repos

Authored-by: Fu Chen <cfmcgrady@gmail.com>
Signed-off-by: ulysses-you <ulyssesyou@apache.org>
(cherry picked from commit 216560ae425416f29257ef8768077c6db0feafd1)
Signed-off-by: ulysses-you <ulyssesyou@apache.org>