[KYUUBI #7135] Fix cannot access /tmp/engine-archives: No such file or directory
### Why are the changes needed?

Fix
```
Run ls -lh /tmp/engine-archives
ls: cannot access '/tmp/engine-archives': No such file or directory
Error: Process completed with exit code 2.
```

### How was this patch tested?

GHA

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #7135 from pan3793/gha-cache-fix.

Closes #7135

99ef56082 [Cheng Pan] Fix cannot access /tmp/engine-archives: No such file or directory

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: Cheng Pan <chengpan@apache.org>
(cherry picked from commit c0d4980dabc203b92383275c6aaa1d48e536b8d3)
Signed-off-by: Cheng Pan <chengpan@apache.org>