[KYUUBI #3126] Using markdown 3.3.7 for kyuubi document build
### _Why are the changes needed?_

Close #3126
The error:

```
Running Sphinx v4.5.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 231 source files that are out of date
updating environment: [new config] 231 added, 0 changed, 0 removed
reading sources... [  0%] appendix/index
Extension error (sphinx_markdown_tables):
Handler <function process_tables at 0x102589090> for event 'source-read' threw an exception (exception: TableProcessor.__init__() missing 1 required positional argument: 'config')
make: *** [html] Error 2
```

I checked the lib difference with before, seems the only change is Markdown version.

Before, it was 3.3.7 and now it is 3.4.1.

### _How was this patch tested?_

Re-create the kyuubi virtual env and build docs locally.

Closes #3127 from turboFei/kyuubi_docs.

Closes #3126

ac428ce3 [Fei Wang] nit
38b56bc3 [Fei Wang] Use markdown 3.3.7 for kyuubi documents build

Authored-by: Fei Wang <fwang12@ebay.com>
Signed-off-by: Fei Wang <fwang12@ebay.com>