[KYUUBI #4450] Ignore unknown fields `policyPriority` when reading policy json file
### _Why are the changes needed?_

To fix #4450.
- allow ignoring unknown fields in policy file for testing which brought by Ranger version changes

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "policyPriority" (class org.apache.ranger.plugin.model.RangerPolicy), not marked as ignorable (21 known properties: "denyPolicyItems", "resources", "guid", "resourceSignature", "name", "policyType", "allowExceptions", "policyItems", "isAuditEnabled", "updatedBy", "service", "updateTime", "isEnabled", "version", "id", "description", "createdBy", "createTime", "denyExceptions", "dataMaskPolicyItems", "rowFilterPolicyItems"])
```

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

Closes #4455 from bowenliang123/authz-unknown-fields.

Closes #4450

592a9545d [liangbowen] ignore unknown fields in json mapper

Authored-by: liangbowen <liangbowen@gf.com.cn>
Signed-off-by: Cheng Pan <chengpan@apache.org>
(cherry picked from commit 889dbc6bf0533ff3b599b4551d4b3ae0544203ca)
Signed-off-by: Cheng Pan <chengpan@apache.org>